### ISSUE TITLE
script missing

### ISSUE THREAD

**Issue by fabryx87** [dhruva-code/zabbix-templates#1]
Hi, 
In first of all I would like to thank you for your work.
I would let you know that the repository is missing the script file, so this template is not usable.
thanks

**Comment by dhruva-code** [comment]
Hi fabryx87,

This is an XML template which needs to be imported into Zabbix server and then it works. However i will upload detailed instructions on how to import it and how it works.

Thank you.

**Comment by dhruva-code** [comment]
Hi fabryx87,

I just uploaded the xml template file only which needs to be imported into Zabbix.

Thankyou.
